version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run unit tests with Maven
          command: mvn test
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Make docs
          command: mvn javadoc:javadoc
      - persist_to_workspace:
          root: target/site
          paths: apidocs
      - codecov/upload

orbs:
  codecov: codecov/codecov@4.0.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
