version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run unit tests with Maven
          command: mvn test
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Make docs
          command: mvn javadoc:javadoc
      - persist_to_workspace:
          root: target/site
          paths: apidocs
      - codecov/upload
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: target/site
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@klukas.net"
            git config user.name "ci-build"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            echo "Deploying docs to gh-pages branch"
            gh-pages --dist apidocs

orbs:
  codecov: codecov/codecov@4.0.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - docs-deploy:
          requires:
            - build
          filters:
            branches:
              only: master
