name: Upload Coverage Reports

on:
  push:
    branches:
      - master

jobs:
  upload-to-codecov:
    runs-on: ubuntu-latest
    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      env:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: NicolasUrban2/ceri-m1-techniques-de-test
